title: Oxynet
description: Where AI meets CPET
show_downloads: true
google_analytics:
remote_theme: pages-themes/cayman

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
