swagger: '2.0'
info:
  title: Read JSON ET Data API
  description: Endpoint for reading JSON data in ET format and performing inference
  version: '1.0.0'
paths:
  /read_json_ET:
    post:
      summary: Read and process JSON data (POST method)
      description: Reads JSON data in ET format from the request body and performs inference.
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - in: body
          name: data
          description: JSON data in ET format
          required: true
          schema:
            type: object
            example: {"key1": "value1", "key2": "value2"}
      responses:
        '200':
          description: Successful inference.
          schema:
            type: object
            properties:
              estimates:
                type: object
                description: Dictionary of inference estimates.
        '400':
          description: Bad request. Invalid JSON data format.

    get:
      summary: Read and process JSON data (GET method)
      description: Reads JSON data in ET format from the query parameter and performs inference.
      produces:
        - application/json
      parameters:
        - in: query
          name: data
          description: JSON data in ET format
          required: true
          type: string
          example: {"key1": "value1", "key2": "value2"}
      responses:
        '200':
          description: Successful inference.
          schema:
            type: object
            properties:
              estimates:
                type: object
                description: Dictionary of inference estimates.
        '400':
          description: Bad request. Invalid JSON data format.
